# Generated by Django 4.2.6 on 2023-10-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_exercise_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_tracker',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
